INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (3765, 'simple', 11, 10, 3727, null);
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13332, 'arabic_stem', 11, 10, 13331, 'language = ''arabic''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13334, 'armenian_stem', 11, 10, 13331, 'language = ''armenian''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13336, 'basque_stem', 11, 10, 13331, 'language = ''basque''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13338, 'catalan_stem', 11, 10, 13331, 'language = ''catalan''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13340, 'danish_stem', 11, 10, 13331, 'language = ''danish'', stopwords = ''danish''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13342, 'dutch_stem', 11, 10, 13331, 'language = ''dutch'', stopwords = ''dutch''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13344, 'english_stem', 11, 10, 13331, 'language = ''english'', stopwords = ''english''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13346, 'finnish_stem', 11, 10, 13331, 'language = ''finnish'', stopwords = ''finnish''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13348, 'french_stem', 11, 10, 13331, 'language = ''french'', stopwords = ''french''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13350, 'german_stem', 11, 10, 13331, 'language = ''german'', stopwords = ''german''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13352, 'greek_stem', 11, 10, 13331, 'language = ''greek''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13354, 'hindi_stem', 11, 10, 13331, 'language = ''hindi''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13356, 'hungarian_stem', 11, 10, 13331, 'language = ''hungarian'', stopwords = ''hungarian''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13358, 'indonesian_stem', 11, 10, 13331, 'language = ''indonesian''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13360, 'irish_stem', 11, 10, 13331, 'language = ''irish''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13362, 'italian_stem', 11, 10, 13331, 'language = ''italian'', stopwords = ''italian''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13364, 'lithuanian_stem', 11, 10, 13331, 'language = ''lithuanian''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13366, 'nepali_stem', 11, 10, 13331, 'language = ''nepali'', stopwords = ''nepali''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13368, 'norwegian_stem', 11, 10, 13331, 'language = ''norwegian'', stopwords = ''norwegian''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13370, 'portuguese_stem', 11, 10, 13331, 'language = ''portuguese'', stopwords = ''portuguese''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13372, 'romanian_stem', 11, 10, 13331, 'language = ''romanian''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13374, 'russian_stem', 11, 10, 13331, 'language = ''russian'', stopwords = ''russian''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13376, 'serbian_stem', 11, 10, 13331, 'language = ''serbian''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13378, 'spanish_stem', 11, 10, 13331, 'language = ''spanish'', stopwords = ''spanish''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13380, 'swedish_stem', 11, 10, 13331, 'language = ''swedish'', stopwords = ''swedish''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13382, 'tamil_stem', 11, 10, 13331, 'language = ''tamil''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13384, 'turkish_stem', 11, 10, 13331, 'language = ''turkish'', stopwords = ''turkish''');
INSERT INTO pg_catalog.pg_ts_dict (oid, dictname, dictnamespace, dictowner, dicttemplate, dictinitoption) VALUES (13386, 'yiddish_stem', 11, 10, 13331, 'language = ''yiddish''');